rhinitis_med = {
    "Antihistamine / Corticosteroid": [
        "fluticasone",
        "Dymista",
    ],
    "Antihistamine / Decongestant": [
        "pseudoephedrine",
        "Sudafed",
        "A-Phedrin",
        "Allegra-D",
        "Aphedrid",
        "Bromfed DM",
        "Cheratussin DAC",
        "Claritin-D",
        "Genaphed",
        "Histafed",
        "Nucofed",
        "P-V-Tussin",
        "Q-Fed",
        "Semprex-D",
        "Sudogest",
        "Vi-Sudo",
        "ZyrTEC-D",
        "Clarinex-D",
        "Contac Cold",
        "Alavert D",
        "Wal-Phed",
        "Ambifed-G CD",
        "Ambifed CD",
        "Tekral",
        "Mar-cof BP",
        "Aller-Tec D",
        "Wal Zyr D",
        "Cetiri-D",
        "Biotussin",
        "Wal-Act",
        "Wal-itin D",
        "Lortuss EX",
        "Wal-Fex D",
        "M-End Max D",
        "Stahist AD",
        "Statuss Green"
        "Zephrex-D",
        "Nexafed",
        "Allerclear",
        "Zodryl DEC",
        "Zodryl DAC",
        "Hycofenix",
        "Wal-Dryl-D Allergy",
    ],
    "Antihistimine": [
        "diphenhydrAMINE",
        "azelastine",
        "cetirizine",
        "loratadine",
        "ZyrTEC",
        "fexofenadine",
        "Benadryl",
        "Claritin",
        "Astelin",
        "desloratadine",
        "Clarinex",
        "Allegra",
        "levocetirizine",
        "Xyzal",
    ],
    "Bronchodilator": [
        "ipratropium",
        "Atrovent",
    ],
    "Corticosteroid": [
        "beclomethasone",
        "triamcinolone",
        "budesonide",
        "flunisolide",
        "fluticasone",
        "Flonase",
        "mometasone",
        "Beconase",
        "Nasacort",
        "Nasonex",
        "Rhinocort",
        "Qvar",
        "ciclesonide",
        "Omnaris",
        "Veramyst",
        "Aerospan",
        "Qnasl",
    ],
    "Leukotriene Receptor Antagonists": [
        "montelukast",
        "Singulair",
    ],
    "Mast cell stablizer": [
        "cromolyn",
        "Nasalcrom",
    ]
}
