"""add contention and claim models

Revision ID: 20aeb06ba5b7
Revises: 
Create Date: 2023-08-15 05:05:49.284602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20aeb06ba5b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vets_api_claim_id', sa.Integer(), nullable=True),
    sa.Column('vets_api_form526_submission_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_id'), 'claim', ['id'], unique=False)
    op.create_index(op.f('ix_claim_vets_api_claim_id'), 'claim', ['vets_api_claim_id'], unique=True)
    op.create_table('contentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnostic_code', sa.Integer(), nullable=True),
    sa.Column('classification_code', sa.Integer(), nullable=True),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentions_id'), 'contentions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contentions_id'), table_name='contentions')
    op.drop_table('contentions')
    op.drop_index(op.f('ix_claim_vets_api_claim_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_id'), table_name='claim')
    op.drop_table('claim')
    # ### end Alembic commands ###
