"""automated migration message

Revision ID: 4df3c3830166
Revises: 548de336b7df
Create Date: 2023-11-02 13:04:23.454313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df3c3830166'
down_revision: Union[str, None] = '548de336b7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mason_model_not_real_model_delete_me', sa.Column('vbms_submitted_claim_id', sa.Integer(), nullable=True))
    op.add_column('mason_model_not_real_model_delete_me', sa.Column('email_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mason_model_not_real_model_delete_me', 'email_address')
    op.drop_column('mason_model_not_real_model_delete_me', 'vbms_submitted_claim_id')
    # ### end Alembic commands ###
