"""create claims and contentions tables

Revision ID: 60e555f39d16
Revises:
Create Date: 2024-04-17 12:24:39.201357

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60e555f39d16"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claims",
        sa.Column("vbms_claim_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("vbms_claim_id"),
    )
    op.create_table(
        "contentions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contentions")
    op.drop_table("claims")
    # ### end Alembic commands ###
