"""automated migration message

Revision ID: 78da658f9506
Revises:
Create Date: 2023-11-07 15:12:55.292892

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78da658f9506'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mason_model_not_real_model_delete_me',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vets_api_claim_id', sa.Integer(), nullable=True),
    sa.Column('vets_api_form526_submission_id', sa.Integer(), nullable=True),
    sa.Column('vbms_submitted_claim_id', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mason_model_not_real_model_delete_me_id'), 'mason_model_not_real_model_delete_me', ['id'], unique=False)
    op.create_index(op.f('ix_mason_model_not_real_model_delete_me_vets_api_claim_id'), 'mason_model_not_real_model_delete_me', ['vets_api_claim_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mason_model_not_real_model_delete_me_vets_api_claim_id'), table_name='mason_model_not_real_model_delete_me')
    op.drop_index(op.f('ix_mason_model_not_real_model_delete_me_id'), table_name='mason_model_not_real_model_delete_me')
    op.drop_table('mason_model_not_real_model_delete_me')
    # ### end Alembic commands ###
