"""added va_gov_claim_id to claim model

Revision ID: b4cd77abb5f1
Revises: 60e555f39d16
Create Date: 2024-04-18 17:19:03.368712

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b4cd77abb5f1'
down_revision: Union[str, None] = '60e555f39d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('va_gov_claim_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'va_gov_claim_id')
    # ### end Alembic commands ###
