source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 3.3.0"

gem 'cgi', '~> 0.3.6' # Address CVE-2021-41819
gem 'bunny', '>= 2.13.0'
gem 'activesupport', '~> 6.0'
gem 'bgs_ext', git: 'https://github.com/department-of-veterans-affairs/bgs-ext.git', require: 'bgs'
gem 'rexml', '>= 3.2.7'

group :development, :test do
  gem 'rspec'
end
