med_dict = {
    "Anti-Inflammatory/Bronchodilator/Corticosteroid/Immuno-Suppressive": [
        "Advair Diskus",
        "Advair HFA",
        "AirDuo Digihaler",
        "AirDuo RespiClick",
        "Wixela Inhub",
        "Flovent",
        "QVAR RediHaler",
        "Symbicort",
        "Trelegy Ellipta",
        "Fluticasone",
        "Mometasone",
        "Propel",
        "Ryaltris",
        "Flonase Sensimist",
    ],
    "Anti-Inflammatory/Corticosteroid/Immuno-Suppressive": [
        "Medrol",
        "MILLIPRED",
        "Rayos",
        "Orapred",
        "Pediapred",
        "Veripred",
        "Aerospan",
        "Alvesco",
        "Asmanex",
        "Breo Ellipta",
        "Dulera",
        "Arnuity",
        "Pulmicort",
        "Methylprednisolone",
        "Prednisone",
        "Flunisolide",
        "Budesonide",
        "Beclomethasone",
        "Qnasl",
        "Beconase",
        "Fluticasone Furoate",  # could cause duplication problem
    ],
    "Anti-Inflammatory/Immuno-Suppressive": [
        "Cinqair",
    ],
    "Anti-Inflammatory/Bronchodilator": [
        "Serevent diskus",
        "Singulair",
        "Salmeterol",
        "Vilanterol",
        "Formoterol",
        "Breyna",
        "Perforomist",
        "Montelukast",
        "Tiotropium",
        "Vilanterol",
        "Zileuton",
    ],
    "Bronchodilator/Used in Respiratory Failure": [
        "Adrenalin",
        "Metaproterenol",
        "Epinephrine",
        "Primatene Mist Inhaler",
        "Albuterol",
        "Levalbuterol",
    ],
    "Corticosteroid/Immuno-Suppressive": [
        "Deltasone",
        "Armonair",
        "Ciclesonide",
        "Omnaris",
        "Zetonna",
    ],
    "Bronchodilator": [
        "EpiPen Jr",
        "Auvi-Q",
        "Symjepi",
        "Ventolin HFA",
        "Proventil HFA",
        "ProAir",
        "AccuNeb",
        "Xopenex",
        "Spiriva Respimat",  # consider splitting
        "Umeclidinium",
    ],
    "Anti-Inflammatory": [
        "Accolate",
        "Dupixent",
        "Fasenra",
        "Nucala",
        "Xolair",
        "Zyflo",
        "Zafirlukast",
        "Reslizumab",
        "Dupilumab",
        "Benralizumab",
        "Mepolizumab",
        "Omalizumab",
    ],
}
