med_dict = {
    "Anti-Inflammatory/Bronchodilator/Corticosteroid/Immuno-Suppressive": {
        "advair",
        "airduo",
        "wixela",
        "flovent",
        "qvar redihaler",
        "symbicort",
        "trelegy ellipta",
        "fluticasone",
        "mometasone",
        "propel",
        "ryaltris",
        "flonase sensimist",
    },
    "Anti-Inflammatory/Corticosteroid/Immuno-Suppressive": {
        "medrol",
        "millipred",
        "rayos",
        "orapred",
        "pediapred",
        "veripred",
        "aerospan",
        "alvesco",
        "asmanex",
        "breo ellipta",
        "dulera",
        "arnuity",
        "pulmicort",
        "methylprednisolone",
        "prednisone",
        "prednisolone",
        "flunisolide",
        "budesonide",
        "beclomethasone",
        "qnasl",
        "beconase",
    },
    "Anti-Inflammatory/Immuno-Suppressive": {
        "cinqair",
    },
    "Anti-Inflammatory/Bronchodilator": {
        "serevent diskus",
        "singulair",
        "salmeterol",
        "vilanterol",
        "formoterol",
        "breyna",
        "perforomist",
        "montelukast",
        "tiotropium",
        "vilanterol",
        "zileuton",
        "formoterol fumarate",
        "tiotropium bromide"
    },
    "Bronchodilator/Used in Respiratory Failure": {
        "adrenalin",
        "metaproterenol",
        "epinephrine",
        "primatene",
        "albuterol",
        "levalbuterol",
    },
    "Corticosteroid/Immuno-Suppressive": {
        "deltasone",
        "armonair",
        "ciclesonide",
        "omnaris",
        "zetonna",
    },
    "Bronchodilator": {
        "epipen",
        "auvi-q",
        "symjepi",
        "ventolin hfa",
        "proventil hfa",
        "proair",
        "accuneb",
        "xopenex",
        "spiriva respimat",
        "umeclidinium",
    },
    "Anti-Inflammatory": {
        "accolate",
        "dupixent",
        "fasenra",
        "nucala",
        "xolair",
        "zyflo",
        "zafirlukast",
        "reslizumab",
        "dupilumab",
        "benralizumab",
        "mepolizumab",
        "omalizumab",
    },
}


asthma_medications = {
    "Aerochamber",
    "Albuterol",
    "Beclomethasone",
    "Benralizumab",
    "Budesonide",
    "Ciclesonide",
    "Fluticasone",
    "Levalbuterol",
    "Mepolizumab",
    "Methylprednisolone",
    "Mometasone",
    "Montelukast",
    "Omalizumab",
    "Prednisone",
    "Reslizumab",
    "Salmeterol",
    "Theophylline",
    "Zafirlukast",
    "Zileuton",
    "Asthma",
    "Breath",
    "Inhal",
    "Puff",
    "SOB",
}