# This file is referenced from local.python.container-service-convention.
# It acts as the default Dockerfile for Python-based containers, i.e., those created by build.gradle
# that use the local.python.container-service-convention plugin.
# To override this file, create a src/docker/Dockerfile file in your Gradle module.
ARG BASE_IMAGE="python:3.10-alpine"
FROM ${BASE_IMAGE}

# hadolint ignore=DL3018
RUN apk update && apk --no-cache upgrade && apk add git && rm -rf /var/cache/apk/*

RUN adduser --disabled-password tron

ARG HEALTHCHECK_PORT_ARG
ENV HEALTHCHECK_PORT=${HEALTHCHECK_PORT_ARG}
ARG HEALTHCHECK_CMD_ARG="curl --fail http://localhost:${HEALTHCHECK_PORT}/health || exit 1"
ENV HEALTHCHECK_CMD=${HEALTHCHECK_CMD_ARG}
HEALTHCHECK CMD eval $HEALTHCHECK_CMD

WORKDIR /app
ARG ENTRYPOINT_FILE=entrypoint.sh
# Workaround to copy ENTRYPOINT_FILE that may not exist
# https://stackoverflow.com/a/46801962
# Copy script that runs entrypoint.sh if it exists
COPY set-env-secrets.src entrypoint-wrapper.sh ${ENTRYPOINT_FILE}* ./

# Used to specify the service folder you want to build if running locally
# No longer write *.pyc files to disk
ENV PYTHONDONTWRITEBYTECODE 1
# Send logs directly to container
ENV PYTHONUNBUFFERED 1

# === Image layers above this line are general and will be reused as cache when building the image.
# Put commands that produce project-specific image layers below this line.

# Copy over all files specified in local.python.container-service-convention
COPY . ./
RUN pip install --upgrade pip --no-cache-dir -r requirements.txt

RUN chmod +x ./*.sh && chown -R tron /app
USER tron
# The exec form of the Dockerfile ENTRYPOINT is used so that there is no shell wrapping the Java process.
# The advantage is that the java process responds to KILL signals sent to the container.
ENTRYPOINT ["/app/entrypoint-wrapper.sh"]
