medications = {'carmustine',
               'CISplatin',
               'cyclophosphamide',
               'etoposide',
               'lomustine',
               'methotrexate',
               'procarbazine',
               'vinCRIStine',
               'vinCRIStine sulfate',
               'etoposide phosphate',
               'temozolomide',
               'CARBOplatin',
               'irinotecan',
               'procarbazine hydrochloride',
               'everolimus',
               'Paraplatin',
               'irinotecan hydrochloride',
               'Camptosar',
               'Matulane',
               'Gliadel',
               'Toposar',
               'cyclophosphamide lyophilized',
               'Vincasar',
               'bevacizumab',
               'Temodar',
               'Etopophos',
               'Trexall',
               'methotrexate sodium',
               'Avastin',
               'BiCNU',
               'carmustine Drug Implant',
               'carmustine Drug Implant [Gliadel]',
               'cyclophosphamide / mannitol',
               'Afinitor',
               'Zortress',
               'vinCRIStine sulfate liposome',
               'vinCRIStine liposome',
               'Marqibo',
               'Otrexup',
               'Rasuvo',
               'Gleostine',
               'cyclophosphamide anhydrous',
               'methotrexate Auto-Injector',
               'methotrexate Auto-Injector [Otrexup]',
               'methotrexate Auto-Injector [Rasuvo]',
               'irinotecan hydrochloride liposome',
               'irinotecan liposomal',
               'Onivyde',
               'Xatmep',
               'bevacizumab-awwb',
               'Mvasi',
               'bevacizumab-bvzr',
               'Zirabev',
               'Hemady',
               'Reditrex',
               'bevacizumab-maly',
               'Alymsys'}