medications = {
    "Lung": {
        "otrexup",
        "reditrex",
        "trexall",
        "xatmep"
    },
    "Lung (non-small cell)": {
        "afatinib",
        "afatinib dimaleate",
        "alecensa",
        "alectinib",
        "alunbrig",
        "alunbrig initiation pack",
        "amivantamab",
        "amivantamab-vmjw",
        "avastin",
        "bevacizumab",
        "brigatinib",
        "camptosar",
        "capmatinib",
        "capmatinib hydrochloride",
        "ceritinib",
        "crizotinib",
        "cyramza",
        "dabrafenib",
        "dabrafenib mesylate",
        "dacomitinib",
        "enhertu",
        "entrectinib",
        "erlotinib",
        "etopophos",
        "etoposide",
        "etoposide phosphate",
        "exkivity",
        "fam-trastuzumab deruxtecan-nxki",
        "gavreto",
        "gefitinib",
        "gilotrif",
        "hycamtin",
        "injection",
        "iressa",
        "irinotecan",
        "irinotecan hydrochloride",
        "irinotecan hydrochloride liposome",
        "irinotecan liposomal",
        "larotrectinib",
        "larotrectinib sulfate",
        "lorbrena",
        "lorlatinib",
        "lung (non small cell), pharynx",
        "lurbinectedin",
        "mekinist",
        "mobocertinib",
        "mobocertinib succinate",
        "necitumumab",
        "onivyde",
        "osimertinib",
        "osimertinib mesylate",
        "portrazza",
        "pralsetinib",
        "ramucirumab",
        "retevmo",
        "rozlytrek",
        "rybrevant",
        "selpercatinib",
        "tabrecta",
        "tafinlar",
        "tagrisso",
        "tarceva",
        "tepmetko",
        "tepotinib",
        "tepotinib hydrochloride",
        "toposar",
        "topotecan",
        "topotecan hydrochloride",
        "trametinib",
        "trametinib dimethyl sulfoxide",
        "trastuzumab",
        "vitrakvi",
        "vizimpro",
        "xalkori",
        "zepzelca",
        "zykadia"
    },
    "Lung (small cell)": {
        "atezolizumab",
        "durvalumab",
        "imfinzi",
        "tecentriq"
    },
    "Multiple": {
        "abraxane",
        "capecitabine",
        "carboplatin",
        "cisplatin",
        "docetaxel",
        "docetaxel anhydrous",
        "keytruda",
        "methotrexate",
        "methotrexate auto-injector",
        "methotrexate auto-injector [otrexup]",
        "methotrexate sodium",
        "nivolumab",
        "opdivo",
        "paclitaxel",
        "paclitaxel poliglumex",
        "paclitaxel protein-bound",
        "paraplatin",
        "pembrolizumab",
        "xeloda"
    }
}
