"""
Script for programmatically detecting changes to the database schema and
creating them in the VRO flywheel migrations folder, so that the db-init
service can properly CRUD postgres tables
"""

import os
import subprocess
import sys

from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected


def are_database_changes():
    cmd = ['alembic', 'check']  # Command to execute
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE)  # Execute the command
    output, error = process.communicate()
    return 'New upgrade operations detected' in output.decode('utf-8')

# def generate_new_migration():
#     cmd = ['alembic', 'revision', '--autogenerate', '-m', '<automated migration message>']
#     process = subprocess.Popen(cmd, stdout=subprocess.PIPE)  # Execute the command
#     output, error = process.communicate()
#     print('output:')
#     print(output.decode('utf-8'))
#
#     print('========================')
#
#     print('error:')
#     print(error)

def generate_new_migration(alembic_cfg):
    revision_script = command.revision(alembic_cfg, autogenerate=True, message='automated migration message')
    return revision_script.path

def get_revision_hash(migration_filepath):
    filename = os.path.basename(migration_filepath)
    return filename.split('_')[0]

def is_higher_migration(first_version_num, second_version_num):
    raise Exception('unimplemented')

def increment_version_number(version_number):
    raise Exception('unimplemented')

def generate_flyway_migration_version():
    """
    '../../db-init/src/main/resources/database/migrations
    """
    # ls files that start w/ V*
    # get the highest number
    # increment by 1
    # return the new version number
    migration_files = os.listdir('../../db-init/src/main/resources/database/migrations')
    migration_files = [f for f in migration_files if f.startswith('V')]
    latest_migration_number = None
    for migration_file in migration_files:
        migration_number_only = migration_file[1:].split('_')[0]
        if latest_migration_number is None or is_higher_migration(migration_number_only, latest_migration_number):
            latest_migration_number = migration_number_only
    return increment_version_number(latest_migration_number)


def generate_flyway_migration(new_migration_path):
    """
    alembic upgrade <revision-hash> --sql > new_sql_file.sql
    mv new_sql_file.sql abd-vro/db-init/src/main/resources/database/migrations/domain_cc_<hash>_migration.sql
    """
    revision_hash = get_revision_hash(new_migration_path)
    cmd = ['alembic', 'upgrade', revision_hash, '--sql', '>', 'new_sql_file.sql']
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE)  # Execute the command
    process.communicate()

    # new_sql_migration_filename = f'abd-vro/db-init/src/main/resources/database/migrations/domain_cc_{revision_hash}_migration.sql'
    new_migration_name = f'{generate_flyway_migration_version()}_domain_cc_{revision_hash}_migration.sql'
    new_sql_migration_filepath = os.path.join('.', f'../../db-init/src/main/resources/database/migrations/{new_migration_name}')
    cmd = ['mv', 'new_sql_file.sql', new_sql_migration_filepath]
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE)  # Execute the command
    process.communicate()


def main():
    # check if there are any changes to apply
    os.chdir('cc-app')
    alembic_cfg = Config("./alembic.ini")
    try:
        command.check(alembic_cfg)
    except AutogenerateDiffsDetected:
        print('handling')
        new_migration_path = generate_new_migration(alembic_cfg)
        generate_flyway_migration(new_migration_path)
    else:
        print('no new changes to apply')
    # print('have changes to apply')
    # generate_new_migration()
    #
    # print('exiting anyway')
    # sys.exit(100)
    #
    # # try to run alembic revision --autogenerate -m "<message describing change>"
    # # if migrations to apply, run alembic upgrade head
    # # alembic upgrade < revision - hash > --sql > new_sql_file.sql
    # # generate a migration version # compatible w/ flywheel
    # # mv the new_sql_file.sql to the flywheel migrations folder
    # # restart postgres-service, or re-run db-init


if __name__ == '__main__':
    main()
