medications = {"Biologic response modifier": {
    "aldesleukin",
    "Proleukin",
    "Pegintron",
    "peginterferon",

    "Sylatron",
},
"Immunotherapy": {
    "pembrolizumab",
    "Keytruda",
    "nivolumab",
    "Opdivo",
    "ipilimumab",
    "Yervoy",
    "ropeginterferon",
    "Besremi",
    "tebentafusp",
    "Kimmtrak",
    "nelatlimab",
    "relatlimab",
    "Opdualag",
},
"Oncolytic virus therapy": {
    "herpesvirus",
    "Imlygic",
    "talimogene",
    "laherparepvec",
},
"Systemic chemotherapy": {
    "aldesleukin",
    "Proleukin",
    "peginterferon",
    "Pegintron",
    "ipilimumab",
    "Yervoy",
    "Sylatron",
    "vemurafenib",
    "Zelboraf",
    "dacarbazine",
    "Intron",
    "Proleukin",
    "trametinib",
    "Mekinist",
    "Tafinlar",
    "dabrafenib",
    "Cotellic",
    "encorafenib",
    "Braftovi",
    "binimetinib",
    "Mektovi",
}}
