antibiotics = {
    "Augmentin",
    "Bactrim",
    "Levaquin",
    "SMX",
    "Septra",
    "Sulfatrim",
    "TRI-PAK",
    "Z-PAK",
    "Zithromax",
    "amoxicillin",
    "azithromycin",
    "clavulanate",
    "levoFLOXacin",
    "sulfamethoxazole",
    "trimethoprim",
}
