radical_surgery = {
    "Anesthesia for procedures on nose and accessory sinuses; not otherwise specified",
    "Anesthesia for procedures on nose and accessory sinuses; radical surgery",
    "Radical maxillary sinusotomy",
    "Sinusotomy, maxillary (antrotomy); radical (Caldwell-Luc) with removal of antrochoanal polyps",
    "Sinusotomy, sphenoid, with or without biopsy; with mucosal stripping or removal of polyp(s)",
    "Ethmoidectomy; intranasal, anterior",
    "Total ethmoidectomy by intranasal approach",
    "Ethmoidectomy; extranasal, total",
    "Maxillectomy",
    "Maxillectomy; with orbital exenteration",
    "Nasal/sinus endoscopy, surgical with ethmoidectomy; total (anterior and posterior), including frontal sinus "
    "exploration, with removal of tissue from frontal sinus, when performed",
    "Nasal/sinus endoscopy, surgical with ethmoidectomy; partial (anterior)",
    "Nasal/sinus endoscopy, surgical with ethmoidectomy; total (anterior and posterior)",
    "Nasal/sinus endoscopy, surgical with ethmoidectomy; total (anterior and posterior), including sphenoidotomy",
    "Nasal/sinus endoscopy, surgical with ethmoidectomy; total (anterior and posterior), including sphenoidotomy, "
    "with removal of tissue from the sphenoid sinus",
    "Craniofacial approach to anterior cranial fossa; extradural, including lateral rhinotomy, ethmoidectomy, "
    "sphenoidectomy, without maxillectomy or orbital exenteration",
    "Craniofacial approach to extradural lesion of anterior cranial fossa, with lateral rhinotomy, "
    "orbital exenteration, ethmoidectomy, and maxillectomy",
    "Craniofacial approach to anterior cranial fossa; intradural, including unilateral or bifrontal craniotomy, "
    "elevation or resection of frontal lobe, osteotomy of base of anterior cranial fossa",
    "Ethmoid sinustectomy",
    "Maxillectomy",
    "Nasal/sinus endoscopy, surgical; with ethmoidectomy",
}
surgery = {
    "Submucous resection inferior turbinate, partial or complete, any method",
    "Septoplasty of nose",
    "Ablation, soft tissue of inferior turbinates, unilateral or bilateral, any method (eg, electrocautery, "
    "radiofrequency ablation, or tissue volume reduction); superficial",
    "Sinusotomy, maxillary (antrotomy); intranasal",
    "Sphenoid sinusotomy",
    "Sinusotomy frontal; external, simple (trephine operation)",
    "Unilateral frontal sinusotomy by transorbital approach",
    "Obliterative frontal sinusotomy with brow incision",
    "Obliterative frontal sinusotomy with coronal incision",
    "Obliterative frontal sinusotomy with osteoplastic flap and coronal incision",
    "Sinusotomy frontal; nonobliterative, with osteoplastic flap, brow incision",
    "Nonobliterative frontal sinusotomy with osteoplastic flap and coronal incision",
    "Unilateral sinusotomy of 3 or more paranasal sinuses",
    "Nasal/sinus endoscopy, diagnostic; with maxillary sinusoscopy (via inferior meatus or canine fossa puncture)",
    "Nasal/sinus endoscopy, diagnostic; with sphenoid sinusoscopy (via puncture of sphenoidal face or cannulation of "
    "ostium)",
    "Nasal/sinus endoscopy, surgical; with control of nasal hemorrhage",
    "Nasal/sinus endoscopy, surgical; with dacryocystorhinostomy",
    "Nasal/sinus endoscopy, surgical, with maxillary antrostomy",
    "Nasal/sinus endoscopy, surgical; with sphenoidotomy",
    "Nasal/sinus endoscopy, surgical, with sphenoidotomy; with removal of tissue from the sphenoid sinus",
    "Nasal/sinus endoscopy, surgical, with repair of cerebrospinal fluid leak; sphenoid region",
    "Nasal/sinus endoscopy, surgical, with orbital decompression; medial or inferior wall",
    "Nasal/sinus endoscopy, surgical, with optic nerve decompression",
    "Nasal/sinus endoscopy, surgical, with dilation (eg, balloon dilation); maxillary sinus ostium, transnasal or via "
    "canine fossa",
    "Nasal/sinus endoscopy, surgical, with dilation (eg, balloon dilation); sphenoid sinus ostium",
    "Unlisted procedure, accessory sinuses",
    "Anesthesia for procedures on nose and accessory sinuses",
    "Surgical procedures on the accessory sinuses",
    "Incision procedures on the accessory sinuses",
    "Sinusotomy, maxillary (antrotomy)",
    "Sinusotomy, maxillary (antrotomy)",
    "Sinusotomy frontal",
    "Excision procedures on the accessory sinuses",
    "Endoscopy procedures on the accessory sinuses",
    "Nasal/sinus endoscopy, surgical",
    "Nasal/sinus endoscopy, surgical, with repair of cerebrospinal fluid leak",
    "Sinusotomy, sphenoid, with or without biopsy",
    "Other procedures on the accessory sinuses",
    "Nasal/sinus endoscopy, surgical, with orbital decompression",
    "Ablation, soft tissue of inferior turbinates, unilateral or bilateral, any method (eg, electrocautery, "
    "radiofrequency ablation, or tissue volume reduction)",
    "Excision inferior turbinate, partial or complete, any method",
    "Ablation, soft tissue of inferior turbinates, unilateral or bilateral, any method (eg, electrocautery, "
    "radiofrequency ablation, or tissue volume reduction); intramural (ie, submucosal)",
    "Nasal/sinus endoscopy, surgical; with biopsy, polypectomy or debridement (separate procedure)",
    "Nasal/sinus endoscopy, surgical; with concha bullosa resection",
    "Nasal/sinus endoscopy, surgical, with dilation (eg, balloon dilation); frontal sinus ostium",
    "Nasal endoscopy, surgical, ethmoid sinus, placement of drug eluting implant",
}
