med_dict = {
    "Anti-Inflammatory/Bronchodilator/Corticosteroid/Immuno-Suppressive": {
        "advair diskus",
        "advair hfa",
        "airduo digihaler",
        "airduo respiclick",
        "wixela inhub",
        "flovent",
        "qvar redihaler",
        "symbicort",
        "trelegy ellipta",
        "fluticasone",
        "mometasone",
        "propel",
        "ryaltris",
        "flonase sensimist",
    },
    "Anti-Inflammatory/Corticosteroid/Immuno-Suppressive": {
        "medrol",
        "millipred",
        "rayos",
        "orapred",
        "pediapred",
        "veripred",
        "aerospan",
        "alvesco",
        "asmanex",
        "breo ellipta",
        "dulera",
        "arnuity",
        "pulmicort",
        "methylprednisolone",
        "prednisone",
        "flunisolide",
        "budesonide",
        "beclomethasone",
        "qnasl",
        "beconase",
        "fluticasone furoate",
    },
    "Anti-Inflammatory/Immuno-Suppressive": {
        "cinqair",
    },
    "Anti-Inflammatory/Bronchodilator": {
        "serevent diskus",
        "singulair",
        "salmeterol",
        "vilanterol",
        "formoterol",
        "breyna",
        "perforomist",
        "montelukast",
        "tiotropium",
        "vilanterol",
        "zileuton",
    },
    "Bronchodilator/Used in Respiratory Failure": {
        "adrenalin",
        "metaproterenol",
        "epinephrine",
        "primatene mist inhaler",
        "albuterol",
        "levalbuterol",
    },
    "Corticosteroid/Immuno-Suppressive": {
        "deltasone",
        "armonair",
        "ciclesonide",
        "omnaris",
        "zetonna",
    },
    "Bronchodilator": {
        "epipen jr",
        "auvi-q",
        "symjepi",
        "ventolin hfa",
        "proventil hfa",
        "proair",
        "accuneb",
        "xopenex",
        "spiriva respimat",
        "umeclidinium",
    },
    "Anti-Inflammatory": {
        "accolate",
        "dupixent",
        "fasenra",
        "nucala",
        "xolair",
        "zyflo",
        "zafirlukast",
        "reslizumab",
        "dupilumab",
        "benralizumab",
        "mepolizumab",
        "omalizumab",
    },
}
