# frozen_string_literal: true

source "https://rubygems.org"

ruby '~> 2.7.6'

gem 'bunny', ">= 2.13.0"
gem 'activesupport', '~> 6.0'
gem 'bgs_ext', git: 'https://github.com/department-of-veterans-affairs/bgs-ext.git', require: 'bgs'
