#!/bin/bash

# This is a quick and dirty script to generate image_vars_db.src that is compatible with Bash 3.
# This script can be replaced with for example a Gradle task later.

# TODO: we should be more consistent about naming our images. This script will
#       help us migrate to get consistency

helm_image_key() {
  case "$1" in
    postgres) echo "db";;
  esac
}

bash_var_prefix() {
  helm_image_key "$@"
}

nonprod_image_name() {
  VROENV=${2:-dev}
  echo "${VROENV}_$(prod_image_name "$1")"
}

prod_image_name() {
  case "$1" in
    *) echo "vro-$1";;
  esac
}

# These names should match directory names
IMAGES=( postgres )
echo
echo "=== ${#IMAGES[@]} VRO images"
for INDEX in "${!IMAGES[@]}"; do
  echo "[$INDEX]: ${IMAGES[$INDEX]}"
done
echo
echo "=== Verifying folders and files"
{
for IMG in "${IMAGES[@]}"; do
  echo "--- $IMG"
  GRADLE_FOLDER=$(gradle_folder "$IMG")
  ls "$GRADLE_FOLDER/build.gradle"
  echo
done
} >> /dev/null

SRC_FILE=scripts/image_vars_db.src
echo
echo "=== Overwriting $SRC_FILE"
# shellcheck disable=SC2145,SC2016
overwriteSrcFile(){
  VAR_PREFIXES=()
  for IMG in "${IMAGES[@]}"; do
    VAR_PREFIXES+=( "$(bash_var_prefix "$IMG")" )
  done

echo '#!/bin/bash'
echo "# This file is autogenerated -- update and re-run $0 instead."
echo "# Usage: source \"$SRC_FILE\""
echo '# These variables are used in GitHub Actions and deploy scripts.

# Array of VRO images
# shellcheck disable=SC2034'
echo "VRO_IMAGES_ARR=( ${IMAGES[@]} )"
echo '# Usage: for IMG in ${VRO_IMAGES_ARR[@]}; do echo "- $IMG"; done'
echo "export VRO_IMAGES=\"${IMAGES[@]}\""
echo
echo '# Array of variable prefixes
# shellcheck disable=SC2034'
echo "VAR_PREFIXES_ARR=( ${VAR_PREFIXES[@]} )"
echo "export VAR_PREFIXES=\"${VAR_PREFIXES[@]}\""
echo '
# Helper function
# Usage example to get the variable value for app_GRADLE_IMG: GRADLE_IMG_TAG=`getVarValue app _GRADLE_IMG`
getVarValue(){
  local VARNAME=${1}${2}
  echo "${!VARNAME}"
}

# Note: Bash arrays cannot be exported; use this workaround to
#       set the array variable from the string first:'
echo "# IFS=' ' read -ra VAR_PREFIXES_ARR <<< \$VAR_PREFIXES"
echo '# for PREFIX in ${VAR_PREFIXES_ARR[@]}; do
#   echo "## $PREFIX"
#   VARNAME=${PREFIX}_GRADLE_IMG
#   echo "$VARNAME = `getVarValue ${PREFIX} _GRADLE_IMG`"
#   echo
# done

'
  echo
  for IMG in "${IMAGES[@]}"; do
    GRADLE_FOLDER=$(gradle_folder "$IMG")
    echo "# --- $IMG in folder $GRADLE_FOLDER"
    PREFIX=$(bash_var_prefix "$IMG")
    echo "export ${PREFIX}_GRADLE_IMG=\"$(gradle_image_name "$IMG")\""
    echo "export ${PREFIX}_IMG=\"$(prod_image_name "$IMG")\""

    echo "export ${PREFIX}_HELM_KEY=\"$(helm_image_key "$IMG")\""
    echo
  done
  echo '# End of file'
}
overwriteSrcFile > "$SRC_FILE"

images_for_helmchart_values_yaml(){
  local _ENV=$1
  echo '# BEGIN image-names-db.sh replacement block (do not modify this block)
# The following image list is updated by image-names-db.sh'
for PREFIX in "${VAR_PREFIXES_ARR[@]}"; do
  echo "  $(getVarValue "${PREFIX}" _HELM_KEY):
    imageName: ${_ENV}_$(getVarValue "${PREFIX}" _IMG)
    tag: tagPlaceholder"
done
echo '# END image-names-db.sh replacement block (do not modify this block)'
}

# shellcheck source=image_vars_db.src
source "$SRC_FILE"
VALUES_YML_IMAGES=$(images_for_helmchart_values_yaml dev)

if which sed > /dev/null; then
  echo "=== Writing images to helm-serivce-db/values-updated.yaml"
  sed -e '/^# BEGIN image-names-db.sh/,/^# END image-names-db.sh/{ r /dev/stdin' -e ';d;}' \
    helm-service-db/values.yaml <<< "$VALUES_YML_IMAGES" > helm-service-db/values-updated.yaml
  echo "Differences:"
  diff helm-service-db/values.yaml helm-service-db/values-updated.yaml
else
  echo
  echo "=== Paste the following into helm-service-db/values.yaml"
  echo "$VALUES_YML_IMAGES"
fi
