s/io\.va\.starter\.example\.api\.account/gov.va.starter.example.api.claimsubmission/
s/io\.va\.starter\.example\.service\.spi\.account/gov.va.starter.example.service.spi.claimsubmission/
s/io\.va\.starter\.example\.service\.provider\.account/gov.va.starter.example.service.provider.claimsubmission/
s/io\.va\.starter\.example\.controller\.account/gov.va.starter.example.controller.claimsubmission/
s/io\.va\.starter\.example\.api/gov.va.starter.example.api/
s/io\.va\.starter\.example/gov.va.starter.example/
s/io\.va/gov.va/
s/account/claimSubmission/g
s/Account/ClaimSubmission/g
