import csv
import re
import sys
from typing import Any

TABLE_VERSION_PY = '../src/python_src/util/data/table_version.py'
DATA_FILE = '../src/python_src/util/data/Diagnostic Code Lookup Table.csv'


def consolidate_data_files(new_data_file: str) -> dict[int, tuple[Any, Any, Any, Any, Any, Any]] | None:
    original_data = import_file(DATA_FILE)
    data_map: dict[int, tuple[Any, int, Any, Any, Any, Any]] = original_data.copy()

    imported_data = import_file(new_data_file)
    updates = imported_data & data_map.keys()
    adds = updates ^ imported_data.keys()
    msg = f'Loading {len(imported_data)} ratings from "{new_data_file}" | Adds {len(adds)} | Potential Updates {len(updates)}'
    print(msg)

    data_map.update(imported_data)

    new_data = dict(sorted(data_map.items()))

    if new_data == original_data:
        print('No changes detected')
        return None

    return new_data


def import_file(filename: str) -> dict[int, tuple[Any, Any, Any, Any, Any, Any]]:
    diagnostic_code_to_data: dict[int, tuple[Any, Any, Any, Any, Any, Any]] = {}
    with open(filename, 'r') as file:
        csv_reader = csv.reader(file)
        for index, csv_line in enumerate(csv_reader):
            if index == 0:
                continue

            if len(csv_line) != 7:
                raise ValueError(f'Invalid CSV line at index {index}')

            diagnostic_code_str, rated_issue_name, max_rating_str, body_system, category, subcategory, cfr_ref = csv_line

            try:
                diagnostic_code = int(diagnostic_code_str)
            except ValueError:
                raise ValueError(f'Invalid diagnostic code at index {index}: \n{csv_line}')

            rated_issue_name = remove_diagnostic_code_prefix(clean_string(rated_issue_name), diagnostic_code_str)
            diagnostic_code_to_data[diagnostic_code] = (rated_issue_name, max_rating_str, body_system, category, subcategory, cfr_ref)

    return diagnostic_code_to_data


def clean_string(input_string):
    # Remove non-alphanumeric characters, excluding some special characters, from the end of the string
    return re.sub(r'[^\w(){}\[\]°]*$', '', input_string)


def remove_diagnostic_code_prefix(rated_issue_name: str, diagnostic_code_str: str) -> str:
    if rated_issue_name.startswith(diagnostic_code_str):
        return rated_issue_name[len(diagnostic_code_str) :].strip()
    return rated_issue_name


def export_data(data: dict[int, tuple[Any, int, Any, Any, Any, Any]]):
    with open(DATA_FILE, 'w') as file:
        csv_writer = csv.writer(file)
        csv_writer.writerow(['Diagnostic Code', 'Rated Issue Name', 'Max Rating', 'Body System', 'Category', 'Subcategory', 'CFR Reference'])
        for diagnostic_code, data_tuple in data.items():
            csv_writer.writerow([diagnostic_code, *data_tuple])


def increment_table_version():
    with open(TABLE_VERSION_PY, 'r') as file:
        version = int(file.readline().strip().split(' = ').pop())
    with open(TABLE_VERSION_PY, 'w') as file:
        file.write(f'TABLE_VERSION = {version + 1}\n')
        file.write('# auto-generated by dc_lookup_table_updater.py\n')


if __name__ == '__main__':
    new_data_file = sys.argv[1]
    print(new_data_file)
    data = consolidate_data_files(new_data_file)
    if data:
        export_data(data)
        print('Data exported')
        increment_table_version()
        print('Table version incremented')
