FROM eclipse-temurin:17-jre-alpine

# curl is needed for HEALTHCHECK
# hadolint ignore=DL3018
RUN apk update && apk --no-cache add expat=2.5.0-r0 curl && rm -rf /var/cache/apk/*

RUN adduser --no-create-home --disabled-password docker

# 8080 is the default port that spring-actuator uses
ARG HEALTHCHECK_PORT_ARG=8080
ENV HEALTHCHECK_PORT=${HEALTHCHECK_PORT_ARG}
HEALTHCHECK CMD curl --fail http://localhost:${HEALTHCHECK_PORT}/actuator/health || exit 1

# === Image layers above this line are general and will be reused as cache.
# Put commands that produce project-specific image layers below this line.

ARG JAR_FILE
ENV JAR_FILENAME=${JAR_FILE}
WORKDIR /project
COPY ${JAR_FILE} fat.jar

ARG ENTRYPOINT_FILE
# Workaround to copy ENTRYPOINT_FILE that may not exist
# https://stackoverflow.com/a/46801962
# Copy script that runs entrypoint.sh if it exists, otherwise run jar file
COPY entrypoint-default.sh ${ENTRYPOINT_FILE}* ./
RUN chmod +x entrypoint*.sh

USER docker

# https://spring.io/guides/topicals/spring-boot-docker/ states:
# The exec form of the Dockerfile ENTRYPOINT is used so that there is no shell wrapping the Java process.
# The advantage is that the java process responds to KILL signals sent to the container.
ENTRYPOINT ["/project/entrypoint-default.sh"]
