antibiotics = {
    "amoxicillin",
    "sulfamethoxazole",
    "trimethoprim",
    "sulfamethoxazole / trimethoprim",
    "azithromycin",
    "amoxicillin / clavulanate",
    "clavulanate",
    "levoFLOXacin",
    "Zithromax 40 MG/ML Oral Suspension",
    "azithromycin 40 MG/ML Oral Suspension",
    "sulfamethoxazole 100 MG / trimethoprim 20 MG Oral Tablet",
    "Augmentin",
    "Bactrim",
    "Zithromax",
    "sulfamethoxazole 400 MG / trimethoprim 80 MG Oral Tablet",
    "sulfamethoxazole 800 MG / trimethoprim 160 MG Oral Tablet",
    "levoFLOXacin 250 MG Oral Tablet",
    "levoFLOXacin 500 MG Oral Tablet",
    "azithromycin 600 MG Oral Tablet",
    "SMX 40 MG/ML / TMP 8 MG/ML Oral Suspension [Sulfatrim]",
    "Bactrim 400 MG / 80 MG Oral Tablet",
    "Zithromax 20 MG/ML Oral Suspension",
    "Zithromax 600 MG Oral Tablet",
    "Levaquin 250 MG Oral Tablet",
    "Levaquin 500 MG Oral Tablet",
    "Zithromax 250 MG Oral Tablet",
    "Levaquin",
    "Sulfatrim",
    "Zithromax 500 MG Oral Tablet",
    "amoxicillin 50 MG/ML Oral Suspension",
    "sulfamethoxazole 80 MG/ML / trimethoprim 16 MG/ML Oral Suspension",
    "azithromycin 500 MG Oral Tablet",
    "Levaquin 750 MG Oral Tablet",
    "amoxicillin 125 MG Chewable Tablet",
    "amoxicillin 250 MG Oral Capsule",
    "amoxicillin 400 MG Chewable Tablet",
    "amoxicillin 80 MG/ML Oral Suspension",
    "amoxicillin 500 MG Oral Capsule",
    "amoxicillin 500 MG Oral Tablet",
    "amoxicillin 875 MG Oral Tablet",
    "azithromycin 20 MG/ML Oral Suspension",
    "azithromycin 250 MG Oral Tablet",
    "levoFLOXacin 750 MG Oral Tablet",
    "sulfamethoxazole 40 MG/ML / trimethoprim 8 MG/ML Oral Suspension",
    "sulfamethoxazole 80 MG/ML / trimethoprim 16 MG/ML Injectable Solution",
    "amoxicillin 25 MG/ML Oral Suspension",
    "amoxicillin 40 MG/ML Oral Suspension",
    "amoxicillin 200 MG Oral Tablet",
    "amoxicillin 400 MG Oral Tablet",
    "amoxicillin 250 MG / clavulanate 125 MG Oral Tablet",
    "amoxicillin 875 MG / clavulanate 125 MG Oral Tablet",
    "amoxicillin 250 MG Chewable Tablet",
    "amoxicillin 500 MG / clavulanate 125 MG Oral Tablet",
    "amoxicillin 25 MG/ML / clavulanate 6.25 MG/ML Oral Suspension",
    "amoxicillin 50 MG/ML / clavulanate 12.5 MG/ML Oral Suspension",
    "Augmentin 125 MG / 31.25 MG per 5 ML Oral Suspension",
    "Augmentin 250 mg / 62.5 MG per 5 ML Oral Suspension",
    "amoxicillin 80 MG/ML / clavulanate 11.4 MG/ML Oral Suspension",
    "Augmentin (amoxicillin 400 MG / clavulanate 57 MG) per 5 ML Oral Suspension",
    "amoxicillin 120 MG/ML / clavulanate 8.58 MG/ML Oral Suspension",
    "12 HR amoxicillin 1000 MG / clavulanate 62.5 MG Extended Release Oral Tablet",
    "Augmentin ES 600 MG / 42.9 MG per 5 ML Oral Suspension",
    "{3 (azithromycin 500 MG Oral Tablet) } Pack",
    "{6 (azithromycin 250 MG Oral Tablet) } Pack",
    "Z-PAK",
    "TRI-PAK",
    "amoxicillin 775 MG Extended Release Oral Tablet",
    "Augmentin 250-mg Oral Tablet",
    "Augmentin 500-mg Oral Tablet",
    "Augmentin 875-mg Oral Tablet",
    "Bactrim DS 800 MG / 160 MG Oral Tablet",
    "azithromycin 1000 MG Powder for Oral Suspension",
    "Zithromax 1 GM Powder for Oral Suspension",
    "Augmentin XR 12 HR 1000 MG Extended Release Oral Tablet",
    "azithromycin 500 MG Injection",
    "Zithromax 500 MG Injection",
    "5 ML sulfamethoxazole 80 MG/ML / trimethoprim 16 MG/ML Injection",
    "Septra"
}