# frozen_string_literal: true

source "https://rubygems.org"

ruby '~> 2.7.6'

gem 'rspec', '~> 3.0'
gem 'bunny', ">= 2.13.0"
gem 'pry', '>= 0.14.1'
gem 'activesupport', '~> 6.0'
gem 'mini_portile2', '~> 2.8.0'

gem 'erb', '>= 2.2.3'
gem 'prawn'
# TODO: Remove ref once a new release has been made.
gem 'prawn-markup', github: 'puzzle/prawn-markup', ref: 'f7956009df696c9d126843d2d35ff270b9c031cd'
gem 'prawn-table'
